//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_Work__4
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget_items
    {
        public int budget_id { get; set; }
        public string budget_name { get; set; }
        public decimal budget_amount { get; set; }
        public string budget_category { get; set; }
        public System.DateTime budget_month { get; set; }
        public string budget_description { get; set; }
    }
}
