//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_Work__4
{
    using System;
    using System.Collections.Generic;
    
    public partial class expenses
    {
        public int expense_id { get; set; }
        public string expense_name { get; set; }
        public decimal expense_amount { get; set; }
        public System.DateTime expense_date { get; set; }
        public string expense_category { get; set; }
        public string expense_description { get; set; }
    }
}
