//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_Work__4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class finance_dbEntities : DbContext
    {
        public finance_dbEntities()
            : base("name=finance_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accounts> accounts { get; set; }
        public virtual DbSet<budget_items> budget_items { get; set; }
        public virtual DbSet<expenses> expenses { get; set; }
        public virtual DbSet<income> income { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tax_rates> tax_rates { get; set; }
        public virtual DbSet<tax_reporting> tax_reporting { get; set; }
        public virtual DbSet<transactions> transactions { get; set; }
    }
}
