//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_Work__4
{
    using System;
    using System.Collections.Generic;
    
    public partial class income
    {
        public int income_id { get; set; }
        public string income_name { get; set; }
        public decimal income_amount { get; set; }
        public System.DateTime income_date { get; set; }
        public string income_category { get; set; }
        public string income_description { get; set; }
    }
}
