//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_Work__4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_reporting
    {
        public int tax_report_id { get; set; }
        public string tax_report_name { get; set; }
        public System.DateTime tax_report_date { get; set; }
        public decimal tax_report_amount { get; set; }
        public int tax_id { get; set; }
        public virtual tax_rates tax_rates { get; set; }
    }
}
